formatter: markdown

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  {{ .Requirements }}
  
  {{ .Inputs }}
  
  {{ .Footer }}

output:
  file: README.md
  mode: replace
  template: |-
    <!-- Begin tf-docs  -->
    {{ .Content }}
    <!-- End tf-docs -->

output-values:
  enabled: false
  from: ""

# recursive:
#   enabled: true

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true